import{d,a as x,b as A,l as L,u as v,s as u,r as p,h as c,e as _,f as S,c as I}from"./assets/api-dde3f044.js";import{o as N}from"./assets/vendor-a5748273.js";const g=document.querySelector(".backdrop"),C=document.querySelector(".modal-wrapper"),w=document.querySelector("body"),i=document.querySelector(".modal-btn-addremove"),m=document.querySelector(".congrats"),h=document.querySelector(".modal-close"),s={_id:"",title:"",author:"",list_name:"",book_image:"",description:"",amazon_buy_link:"",apple_buy_link:""};async function P(e){try{C.innerHTML="",m.innerHTML="";const t=await d.getBookDescription(e);s._id=t._id,s.title=t.title,s.author=t.author,s.list_name=t.list_name,s.book_image=t.book_image,s.description=t.description,s.amazon_buy_link=t.buy_links[0].url,s.apple_buy_link=t.buy_links[1].url;const o=z(t);C.insertAdjacentHTML("beforeend",o),f(i,e),h.blur(),i.addEventListener("click",T),h.addEventListener("click",y),document.addEventListener("keydown",E),g.addEventListener("click",q)}catch(t){console.log("Error fetching modal:",t)}}function M(e){g.classList.add("modal-open"),w.classList.add("no-scroll"),P(e)}function z(e){return`
      <img class="modal-img-book" src="${e.book_image}" alt="book" />
        
      <div class="modal-book-container-right">
        <div class="modal-book-container">
          <div class="modal-book-info">
            <h3 class="modal-description-title">${e.title}</h3>
            <p class="modal-description-author">${e.author}</p>
          </div>
          <p class="modal-book-description">${e.description}</p>
          <ul class="modal-icons-list">
          <li>
            <a class="modal-book-link" href="${e.buy_links[0].url}" target="_blank"><img class='modal-link-icon-amazon' src="${x}" alt="" width='62' height='19' 
            /></a>
          </li>
          <li>
            <a class="modal-book-link" href="${e.buy_links[1].url}" target="_blank"><img class='modal-link-icon-apple' src="${A}" alt="" width='33' height='32'
            /></a>
          </li>
          </ul>
        </div>
      </div>`}function f(e,t){L.isBookExsist(t)?(e.textContent="remove from the shopping list",m.classList.add("modal-text-congratulations"),e.blur()):(e.textContent="add to shopping list",m.classList.remove("modal-text-congratulations"),e.blur())}function T(e){i.textContent==="add to shopping list"?(D(s),f(i,s._id)):(F(s),f(i,s._id))}function E(e){e.key==="Escape"&&y()}function q(e){e.target===g&&y()}function y(){g.classList.remove("modal-open"),w.classList.remove("no-scroll"),h.removeEventListener("click",y),i.removeEventListener("click",T),document.removeEventListener("keydown",E),g.removeEventListener("click",q)}function D(e){L.addBookToFavorites(e),v(),m.textContent='Сongratulations! You have added the book to the shopping list. To delete, press the button "Remove from the shopping list".'}function F(e){L.removeBookFromFavorites(e),v(),m.textContent=""}function H(e,t){if(u(),e.length===0)try{const o=document.querySelector(".bestsellers-container");o.innerHTML="",p(".bestsellers-container",t),o.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const n=document.querySelector(".book-category-list"),r='<p class = "category-text-empty">Sorry, no books were found for the given category</p>';n.innerHTML=r}catch{console.log("Error fetching modal:",error)}finally{c()}else try{const o=document.querySelector(".bestsellers-container");o.innerHTML="",p(".bestsellers-container",t),o.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const n=document.querySelector(".book-category-list"),r=e.map(({author:l,book_image:a,title:b,_id:k})=>_({author:l,book_image:a,title:b,_id:k})).join("");n.innerHTML=r,n.addEventListener("click",O)}catch{console.log("Error fetching modal:",error)}finally{c()}}async function O(e){if(e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;M(t)}}async function U(){try{const e=document.querySelector(".bestsellers-container");e.innerHTML="",u();const t=await d.getBestSellers();$(t)}catch(e){console.error("Error fetching best sellers:",e)}}function $(e){const t=document.querySelector(".bestsellers-container");c(),t.innerHTML="",p(".bestsellers-container","Best Sellers Books"),t.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const o=document.querySelector(".bestsellers-list"),n=e.map(({books:r,list_name:l})=>`<li class="bestsellers-item">
      <h2 class="bestsellers-category-title">${l}</h2>
      <ul class="bestsellers-books-list">${r.map(({title:a,author:b,book_image:k,_id:j})=>r.length===0?'<p class="category-empty">Sorry, no books were found for the given category!</p>':_({title:a,author:b,book_image:k,_id:j})).join(`
`)}
        </ul>
        <button class="bestsellers-btn" type="button" data-category="${l}">See more</button>
      </li>`).join(`
`);o.insertAdjacentHTML("beforeend",n),o.addEventListener("click",Y),o.addEventListener("click",G)}async function G(e){if(e.preventDefault(),e.target.nodeName==="IMG"||e.target.nodeName==="H3"||e.target.nodeName==="P"){let t=e.target.closest(".book-category-item").dataset.id;M(t)}}async function Y(e){try{if(e.target.nodeName!=="BUTTON")return;let t=e.target.dataset.category;const o=document.querySelector(".sidebar-category-item"),n=document.querySelectorAll(".sidebar-category-item"),r=document.querySelector(".bestsellers-container");r.innerHTML="",u();const l=await d.getSelectedCategory(t);H(l,t),c(),n.forEach(a=>{a.dataset.source===t&&(o.classList.remove("category-active"),a.classList.add("category-active"),a.scrollIntoView({behavior:"instant",block:"center",inline:"nearest"}))}),S()}catch(t){console.log("Error fetching modal:",t)}}const B={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function V(e){return e.sort((o,n)=>o.list_name.localeCompare(n.list_name)),e.map(o=>`<li class='sidebar-category-item' data-source="${o.list_name}">${o.list_name}</li>`).join("")}(async()=>{try{const e=document.querySelector(".bestsellers-container");e.innerHTML="",u();const t=await d.getCategoryList(),o=V(t);B.categoryList.insertAdjacentHTML("beforeend",o),c()}catch(e){console.log(e)}})();B.allCategory.addEventListener("click",async e=>{try{const t=document.querySelector(".bestsellers-container");t.innerHTML="",u();const o=await d.getBestSellers();$(o),c(),S()}catch(t){console.log(t)}});B.categoryList.addEventListener("click",async e=>{if(e.target.classList.contains("sidebar-category-item")){const t=e.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(r=>{r.classList.remove("category-active")}),e.target.classList.add("category-active"),window.scrollTo({top:0,behavior:"smooth"});const n=document.querySelector(".bestsellers-container");n.innerHTML="",u();try{if(!e.target.classList.contains("all-category")){const r=await d.getSelectedCategory(t);H(r,t),c(),S()}}catch(r){console.log(r)}}});N(I,e=>{console.log(e||"you have to log in")});U();v();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".scroll-up");window.addEventListener("scroll",function(){window.scrollY>600?e.classList.add("show"):e.classList.remove("show")}),e.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})})});
//# sourceMappingURL=commonHelpers2.js.map
